// Generated by CoffeeScript 1.3.3
(function() {

  window.search = function(searchString) {
    setResults(searchString, new Demo.Search().search(searchString));
    return log("search('" + searchString + "')");
  };

  window.log = function(commandText) {
    $$.clear();
    return $$.print("executed: <em>" + commandText + "\n</em>");
  };

  window.setResults = function(searchString, results) {
    var text;
    text = results.toString().replace(/,/g, "\n");
    $('#searchString').val(searchString);
    return $('#results').text(text);
  };

}).call(this);
