// Generated by CoffeeScript 1.3.3
(function() {

  Demo.Search = (function() {

    function Search() {}

    Search.prototype.search = function(searchString) {
      var dictionary, matchingWords;
      dictionary = new Demo.Dictionary();
      return matchingWords = _.select(dictionary.words, function(word) {
        return word.match(searchString);
      });
    };

    return Search;

  })();

}).call(this);
